(() => {
  const translations = {
    ta: {'Overview':'முகப்பு','Products':'தயாரிப்புகள்','Branches':'கிளைகள்','Transactions':'பரிவர்த்தனைகள்','Inventory':'கையிருப்பு','Targets':'இலக்குகள்','Upload data':'தரவு பதிவேற்றம்','Dashboard filters':'டாஷ்போர்டு வடிகட்டிகள்','Refine your analysis':'உங்கள் பகுப்பாய்வைச் சீரமைக்கவும்','Branch':'கிளை','Category':'வகை','Channel':'விற்பனை சேனல்','From date':'தொடக்க தேதி','To date':'முடிவு தேதி','Compare by':'ஒப்பிடுக','Daily':'தினசரி','Monthly':'மாதாந்திர','Quarterly':'காலாண்டு','Yearly':'வருடாந்திர','Reset filters':'வடிகட்டிகளை மீட்டமை','Total revenue':'மொத்த வருவாய்','Estimated profit':'மதிப்பிடப்பட்ட லாபம்','Profit margin':'லாப விகிதம்','Transactions':'பரிவர்த்தனைகள்','Sales after discounts':'தள்ளுபடிக்குப் பிந்தைய விற்பனை','Projected contribution':'மதிப்பிடப்பட்ட பங்களிப்பு','Across selected sales':'தேர்ந்தெடுத்த விற்பனைகளில்','units sold':'விற்ற அலகுகள்','Download CSV':'CSV பதிவிறக்கு','Download PDF':'PDF பதிவிறக்கு','Time comparison':'கால ஒப்பீடு','Reporting':'அறிக்கைகள்'},
    si: {'Overview':'සාරාංශය','Products':'නිෂ්පාදන','Branches':'ශාඛා','Transactions':'ගනුදෙනු','Inventory':'තොගය','Targets':'ඉලක්ක','Upload data':'දත්ත උඩුගත කරන්න','Dashboard filters':'ඩෑෂ්බෝඩ් පෙරහන්','Refine your analysis':'ඔබගේ විශ්ලේෂණය සකසන්න','Branch':'ශාඛාව','Category':'කාණ්ඩය','Channel':'විකුණුම් නාලිකාව','From date':'ආරම්භක දිනය','To date':'අවසාන දිනය','Compare by':'සසඳන්න','Daily':'දිනපතා','Monthly':'මාසික','Quarterly':'කාර්තුමය','Yearly':'වාර්ෂික','Reset filters':'පෙරහන් යළි සකසන්න','Total revenue':'මුළු ආදායම','Estimated profit':'ඇස්තමේන්තු ලාභය','Profit margin':'ලාභ අනුපාතය','Sales after discounts':'වට්ටම් පසු විකුණුම්','Projected contribution':'ඇස්තමේන්තු දායකත්වය','Across selected sales':'තෝරාගත් විකුණුම් අතර','units sold':'විකුණුම් ඒකක','Download CSV':'CSV බාගන්න','Download PDF':'PDF බාගන්න','Time comparison':'කාල සැසඳීම','Reporting':'වාර්තාකරණය'}
  };
  let language = localStorage.getItem('retailpulse-language') || 'en';
  const walker = () => document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
  function apply() { const map = translations[language] || {}; const nodes = []; const scan = walker(); while (scan.nextNode()) nodes.push(scan.currentNode); nodes.forEach(node => { const original = node.parentElement?.dataset.originalText || node.nodeValue.trim(); if (!original) return; if (node.parentElement && !node.parentElement.dataset.originalText) node.parentElement.dataset.originalText = original; const replacement = map[original] || original; node.nodeValue = node.nodeValue.replace(original, replacement); }); document.documentElement.lang = language === 'ta' ? 'ta' : language === 'si' ? 'si' : 'en'; document.querySelectorAll('.language-toggle button').forEach(button => button.classList.toggle('active', button.dataset.lang === language)); }
  const control = document.createElement('div'); control.className = 'language-toggle'; control.innerHTML = '<button data-lang="en">EN</button><button data-lang="ta">தமிழ்</button><button data-lang="si">සිං</button>'; control.querySelectorAll('button').forEach(button => button.onclick = () => { language = button.dataset.lang; localStorage.setItem('retailpulse-language', language); apply(); }); document.body.append(control); apply();
})();
